# Generated by Django 3.1 on 2020-09-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='monthly_saving',
        ),
    ]
