# Generated by Django 3.1 on 2020-09-06 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_monthly_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysaving',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 6, 10, 41, 7, 530583, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysaving',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
