# Generated by Django 3.1 on 2020-09-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200906_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlySaving',
        ),
    ]
