# Generated by Django 3.1 on 2020-09-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_auto_20200906_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_saving', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_month_loan', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fine', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loan_amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('remaining_loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('additional_loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
